<?php

/**
 *
 * @return array
 */
function _wpsc_get_countries_data_array() {

	$countries = array(
		array('id' => '1','name' => 'Mauritania','isocode' => 'MR','currency_name' => 'Mauritanian Ouguiya','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MRO','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '2','name' => 'Martinique (French)','isocode' => 'MQ','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '3','name' => 'Malta','isocode' => 'MT','currency_name' => 'Maltese Lira','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MTL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '4','name' => 'Marshall Islands','isocode' => 'MH','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '5','name' => 'Mali','isocode' => 'ML','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '6','name' => 'Maldives','isocode' => 'MV','currency_name' => 'Maldive Rufiyaa','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MVR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '7','name' => 'Malaysia','isocode' => 'MY','currency_name' => 'Malaysian Ringgit','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MYR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '8','name' => 'Malawi','isocode' => 'MW','currency_name' => 'Malawi Kwacha','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MWK','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '9','name' => 'Madagascar','isocode' => 'MG','currency_name' => 'Malagasy Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MGF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '10','name' => 'Macau','isocode' => 'MO','currency_name' => 'Macau Pataca','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MOP','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '11','name' => 'Macedonia','isocode' => 'MK','currency_name' => 'Denar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MKD','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '12','name' => 'Luxembourg','isocode' => 'LU','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '13','name' => 'Lithuania','isocode' => 'LT','currency_name' => 'Lithuanian Litas','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LTL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '14','name' => 'Liechtenstein','isocode' => 'LI','currency_name' => 'Swiss Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CHF','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '15','name' => 'Libya','isocode' => 'LY','currency_name' => 'Libyan Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LYD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '16','name' => 'Liberia','isocode' => 'LR','currency_name' => 'Liberian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'LRD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '17','name' => 'Lesotho','isocode' => 'LS','currency_name' => 'Lesotho Loti','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LSL','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '18','name' => 'Lebanon','isocode' => 'LB','currency_name' => 'Lebanese Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LBP','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '19','name' => 'Latvia','isocode' => 'LV','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '20','name' => 'Laos','isocode' => 'LA','currency_name' => 'Lao Kip','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LAK','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '21','name' => 'Kyrgyzstan','isocode' => 'KG','currency_name' => 'Som','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KGS','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '22','name' => 'Kuwait','isocode' => 'KW','currency_name' => 'Kuwaiti Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KWD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '23','name' => 'Korea, South','isocode' => 'KR','currency_name' => 'Korean Won','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KRW','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '24','name' => 'Korea, North','isocode' => 'KP','currency_name' => 'North Korean Won','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KPW','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '25','name' => 'Kiribati','isocode' => 'KI','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '26','name' => 'Kenya','isocode' => 'KE','currency_name' => 'Kenyan Shilling','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KES','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '27','name' => 'Kazakhstan','isocode' => 'KZ','currency_name' => 'Kazakhstan Tenge','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KZT','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '28','name' => 'Jordan','isocode' => 'JO','currency_name' => 'Jordanian Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'JOD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '29','name' => 'Jersey','isocode' => 'JE','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '30','name' => 'Japan','isocode' => 'JP','currency_name' => 'Japanese Yen','currency_symbol' => '¥','currency_symbol_html' => '&#165;','currency_code' => 'JPY','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '31','name' => 'Jamaica','isocode' => 'JM','currency_name' => 'Jamaican Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'JMD','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '32','name' => 'Ivory Coast','isocode' => 'CI','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '33','name' => 'Italy','isocode' => 'IT','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '34','name' => 'Isle of Man','isocode' => 'IM','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '35','name' => 'Israel','isocode' => 'IL','currency_name' => 'Israeli New Shekel','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ILS','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '36','name' => 'Ireland','isocode' => 'IE','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '37','name' => 'Iraq','isocode' => 'IQ','currency_name' => 'Iraqi Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'IQD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '38','name' => 'Indonesia','isocode' => 'ID','currency_name' => 'Indonesian Rupiah','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'IDR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '39','name' => 'Iran','isocode' => 'IR','currency_name' => 'Iranian Rial','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'IRR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '40','name' => 'India','isocode' => 'IN','currency_name' => 'Indian Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'INR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '41','name' => 'Iceland','isocode' => 'IS','currency_name' => 'Iceland Krona','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ISK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '42','name' => 'Hungary','isocode' => 'HU','currency_name' => 'Hungarian Forint','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'HUF','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '43','name' => 'Hong Kong','isocode' => 'HK','currency_name' => 'Hong Kong Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'HKD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '44','name' => 'Honduras','isocode' => 'HN','currency_name' => 'Honduran Lempira','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'HNL','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '45','name' => 'Heard Island and McDonald Islands','isocode' => 'HM','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '46','name' => 'Haiti','isocode' => 'HT','currency_name' => 'Haitian Gourde','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'HTG','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '47','name' => 'Guyana','isocode' => 'GY','currency_name' => 'Guyana Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'GYD','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '48','name' => 'Guinea Bissau','isocode' => 'GW','currency_name' => 'Guinea-Bissau Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GWP','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '49','name' => 'Guinea','isocode' => 'GN','currency_name' => 'Guinea Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GNF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '50','name' => 'Guernsey','isocode' => 'GF','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '51','name' => 'Guatemala','isocode' => 'GT','currency_name' => 'Guatemalan Quetzal','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'QTQ','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '52','name' => 'Guam (USA)','isocode' => 'GU','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '53','name' => 'Grenada','isocode' => 'GD','currency_name' => 'East Carribean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '54','name' => 'Guadeloupe (French)','isocode' => 'GP','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '55','name' => 'Greenland','isocode' => 'GL','currency_name' => 'Danish Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DKK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '56','name' => 'Greece','isocode' => 'GR','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '19','continent' => 'europe','visible' => '0'),
		array('id' => '57','name' => 'Gibraltar','isocode' => 'GI','currency_name' => 'Gibraltar Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GIP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '58','name' => 'Ghana','isocode' => 'GH','currency_name' => 'Ghanaian Cedi','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GHC','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '59','name' => 'Germany','isocode' => 'DE','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '60','name' => 'Georgia','isocode' => 'GE','currency_name' => 'Georgian Lari','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GEL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '61','name' => 'Gambia','isocode' => 'GM','currency_name' => 'Gambian Dalasi','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'GMD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '62','name' => 'Gabon','isocode' => 'GA','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '63','name' => 'French Southern Territories','isocode' => 'TF','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '64','name' => 'France','isocode' => 'FR','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '65','name' => 'Finland','isocode' => 'FI','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '66','name' => 'Fiji','isocode' => 'FJ','currency_name' => 'Fiji Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'FJD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '67','name' => 'Faroe Islands','isocode' => 'FO','currency_name' => 'Danish Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DKK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '68','name' => 'Falkland Islands','isocode' => 'FK','currency_name' => 'Falkland Islands Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'FKP','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '69','name' => 'Ethiopia','isocode' => 'ET','currency_name' => 'Ethiopian Birr','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ETB','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '70','name' => 'Estonia','isocode' => 'EE','currency_name' => 'Estonian Kroon','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'EEK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '71','name' => 'Eritrea','isocode' => 'ER','currency_name' => 'Eritrean Nakfa','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ERN','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '72','name' => 'Equatorial Guinea','isocode' => 'GQ','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '73','name' => 'El Salvador','isocode' => 'SV','currency_name' => 'El Salvador Colon','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SVC','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '74','name' => 'Egypt','isocode' => 'EG','currency_name' => 'Egyptian Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'EGP','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '75','name' => 'Ecuador','isocode' => 'EC','currency_name' => 'Ecuador Sucre','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ECS','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '76','name' => 'East Timor','isocode' => 'TP','currency_name' => 'Timor Escudo','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TPE','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '77','name' => 'Dominican Republic','isocode' => 'DO','currency_name' => 'Dominican Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DOP','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '78','name' => 'Dominica','isocode' => 'DM','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '79','name' => 'Djibouti','isocode' => 'DJ','currency_name' => 'Djibouti Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DJF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '80','name' => 'Denmark','isocode' => 'DK','currency_name' => 'Danish Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DKK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '81','name' => 'Democratic Republic of Congo','isocode' => 'CD','currency_name' => 'Francs','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CDF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '82','name' => 'Czech Rep.','isocode' => 'CZ','currency_name' => 'Czech Koruna','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CZK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '83','name' => 'Cyprus','isocode' => 'CY','currency_name' => 'Cyprus Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CYP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '84','name' => 'Cuba','isocode' => 'CU','currency_name' => 'Cuban Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CUP','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '85','name' => 'Croatia','isocode' => 'HR','currency_name' => 'Croatian Kuna','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'HRK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '86','name' => 'Costa Rica','isocode' => 'CR','currency_name' => 'Costa Rican Colon','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CRC','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '87','name' => 'Cook Islands','isocode' => 'CK','currency_name' => 'New Zealand Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NZD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '88','name' => 'Congo','isocode' => 'CG','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '89','name' => 'Comoros','isocode' => 'KM','currency_name' => 'Comoros Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KMF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '90','name' => 'Colombia','isocode' => 'CO','currency_name' => 'Colombian Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'COP','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '91','name' => 'Cocos (Keeling) Islands','isocode' => 'CC','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '92','name' => 'Christmas Island','isocode' => 'CX','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '93','name' => 'Chile','isocode' => 'CL','currency_name' => 'Chilean Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CLP','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '94','name' => 'China','isocode' => 'CN','currency_name' => 'Yuan Renminbi','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CNY','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '95','name' => 'Chad','isocode' => 'TD','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '96','name' => 'Central African Republic','isocode' => 'CF','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '97','name' => 'Cayman Islands','isocode' => 'KY','currency_name' => 'Cayman Islands Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'KYD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '98','name' => 'Cape Verde','isocode' => 'CV','currency_name' => 'Cape Verde Escudo','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CVE','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '99','name' => 'Cameroon','isocode' => 'CM','currency_name' => 'CFA Franc BEAC','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XAF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '100','name' => 'Canada','isocode' => 'CA','currency_name' => 'Canadian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'CAD','has_regions' => '1','tax' => '','continent' => 'northamerica','visible' => '1'),
		array('id' => '101','name' => 'Cambodia','isocode' => 'KH','currency_name' => 'Kampuchean Riel','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'KHR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '102','name' => 'Burundi','isocode' => 'BI','currency_name' => 'Burundi Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BIF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '103','name' => 'Burkina Faso','isocode' => 'BF','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '104','name' => 'Bulgaria','isocode' => 'BG','currency_name' => 'Bulgarian Lev','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BGL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '105','name' => 'Brunei Darussalam','isocode' => 'BN','currency_name' => 'Brunei Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'BND','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '106','name' => 'British Indian Ocean Territory','isocode' => 'IO','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '107','name' => 'Brazil','isocode' => 'BR','currency_name' => 'Brazilian Real','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BRL','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '108','name' => 'Bouvet Island','isocode' => 'BV','currency_name' => 'Norwegian Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NOK','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '109','name' => 'Botswana','isocode' => 'BW','currency_name' => 'Botswana Pula','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BWP','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '110','name' => 'Bosnia-Herzegovina','isocode' => 'BA','currency_name' => 'Marka','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BAM','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '111','name' => 'Bolivia','isocode' => 'BO','currency_name' => 'Boliviano','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BOB','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '112','name' => 'Bhutan','isocode' => 'BT','currency_name' => 'Bhutan Ngultrum','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BTN','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '113','name' => 'Bermuda','isocode' => 'BM','currency_name' => 'Bermudian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'BMD','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '114','name' => 'Benin','isocode' => 'BJ','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '115','name' => 'Belize','isocode' => 'BZ','currency_name' => 'Belize Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'BZD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '116','name' => 'Belgium','isocode' => 'BE','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '117','name' => 'Belarus','isocode' => 'BY','currency_name' => 'Belarussian Ruble','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BYB','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '118','name' => 'Barbados','isocode' => 'BB','currency_name' => 'Barbados Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'BBD','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '119','name' => 'Bangladesh','isocode' => 'BD','currency_name' => 'Bangladeshi Taka','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BDT','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '120','name' => 'Bahrain','isocode' => 'BH','currency_name' => 'Bahraini Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'BHD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '121','name' => 'Bahamas','isocode' => 'BS','currency_name' => 'Bahamian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'BSD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '122','name' => 'Azerbaijan','isocode' => 'AZ','currency_name' => 'Azerbaijanian Manat','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AZM','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '123','name' => 'Austria','isocode' => 'AT','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '124','name' => 'Aruba','isocode' => 'AW','currency_name' => 'Aruban Guilder','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AWG','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '125','name' => 'Armenia','isocode' => 'AM','currency_name' => 'Armenian Dram','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AMD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '126','name' => 'Argentina','isocode' => 'AR','currency_name' => 'Argentine Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ARS','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '127','name' => 'Antigua and Barbuda','isocode' => 'AG','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '128','name' => 'Antarctica','isocode' => 'AQ','currency_name' => 'Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'ATA','has_regions' => '0','tax' => '0','continent' => 'antarctica','visible' => '0'),
		array('id' => '129','name' => 'Anguilla','isocode' => 'AI','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '130','name' => 'Angola','isocode' => 'AO','currency_name' => 'Angolan New Kwanza','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AON','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '131','name' => 'Andorra','isocode' => 'AD','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '132','name' => 'American Samoa','isocode' => 'AS','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '133','name' => 'Algeria','isocode' => 'DZ','currency_name' => 'Algerian Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'DZD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '134','name' => 'Albania','isocode' => 'AL','currency_name' => 'Albanian Lek','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ALL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '135','name' => 'Afghanistan','isocode' => 'AF','currency_name' => 'Afghanistan Afghani','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AFA','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '136','name' => 'USA','isocode' => 'US','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '1','tax' => '','continent' => 'northamerica','visible' => '1'),
		array('id' => '137','name' => 'Australia','isocode' => 'AU','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '138','name' => 'United Kingdom','isocode' => 'GB','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '139','name' => 'Mauritius','isocode' => 'MU','currency_name' => 'Mauritius Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MUR','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '140','name' => 'Mayotte','isocode' => 'YT','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '141','name' => 'Mexico','isocode' => 'MX','currency_name' => 'Mexican Nuevo Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MXN','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '142','name' => 'Micronesia','isocode' => 'FM','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '143','name' => 'Moldova','isocode' => 'MD','currency_name' => 'Moldovan Leu','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MDL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '144','name' => 'Monaco','isocode' => 'MC','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '145','name' => 'Mongolia','isocode' => 'MN','currency_name' => 'Mongolian Tugrik','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MNT','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '146','name' => 'Montserrat','isocode' => 'MS','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '147','name' => 'Morocco','isocode' => 'MA','currency_name' => 'Moroccan Dirham','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MAD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '148','name' => 'Mozambique','isocode' => 'MZ','currency_name' => 'Mozambique Metical','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MZM','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '149','name' => 'Myanmar','isocode' => 'MM','currency_name' => 'Myanmar Kyat','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MMK','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '150','name' => 'Namibia','isocode' => 'NA','currency_name' => 'Namibian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NAD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '151','name' => 'Nauru','isocode' => 'NR','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '152','name' => 'Nepal','isocode' => 'NP','currency_name' => 'Nepalese Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NPR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '153','name' => 'Netherlands','isocode' => 'NL','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '154','name' => 'Netherlands Antilles','isocode' => 'AN','currency_name' => 'Netherlands Antillean Guilder','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ANG','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '155','name' => 'New Caledonia (French)','isocode' => 'NC','currency_name' => 'CFP Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XPF','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '156','name' => 'New Zealand','isocode' => 'NZ','currency_name' => 'New Zealand Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NZD','has_regions' => '0','tax' => '12.5','continent' => 'asiapacific','visible' => '0'),
		array('id' => '157','name' => 'Nicaragua','isocode' => 'NI','currency_name' => 'Nicaraguan Cordoba Oro','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NIC','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '158','name' => 'Niger','isocode' => 'NE','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '159','name' => 'Nigeria','isocode' => 'NG','currency_name' => 'Nigerian Naira','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NGN','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '160','name' => 'Niue','isocode' => 'NU','currency_name' => 'New Zealand Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NZD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '161','name' => 'Norfolk Island','isocode' => 'NF','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '162','name' => 'Northern Mariana Islands','isocode' => 'MP','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '163','name' => 'Norway','isocode' => 'NO','currency_name' => 'Norwegian Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NOK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '164','name' => 'Oman','isocode' => 'OM','currency_name' => 'Omani Rial','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'OMR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '165','name' => 'Pakistan','isocode' => 'PK','currency_name' => 'Pakistan Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PKR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '166','name' => 'Palau','isocode' => 'PW','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '167','name' => 'Panama','isocode' => 'PA','currency_name' => 'Panamanian Balboa','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PAB','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '168','name' => 'Papua New Guinea','isocode' => 'PG','currency_name' => 'Papua New Guinea Kina','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PGK','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '169','name' => 'Paraguay','isocode' => 'PY','currency_name' => 'Paraguay Guarani','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PYG','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '170','name' => 'Peru','isocode' => 'PE','currency_name' => 'Peruvian Nuevo Sol','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PEN','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '171','name' => 'Philippines','isocode' => 'PH','currency_name' => 'Philippine Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PHP','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '172','name' => 'Pitcairn Island','isocode' => 'PN','currency_name' => 'New Zealand Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NZD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '173','name' => 'Poland','isocode' => 'PL','currency_name' => 'Polish Zloty','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'PLN','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '174','name' => 'Polynesia (French)','isocode' => 'PF','currency_name' => 'CFP Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XPF','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '175','name' => 'Portugal','isocode' => 'PT','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '176','name' => 'Puerto Rico','isocode' => 'PR','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '177','name' => 'Qatar','isocode' => 'QA','currency_name' => 'Qatari Rial','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'QAR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '178','name' => 'Reunion (French)','isocode' => 'RE','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '179','name' => 'Romania','isocode' => 'RO','currency_name' => 'Romanian Leu','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'RON','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '180','name' => 'Russia','isocode' => 'RU','currency_name' => 'Russian Ruble','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'RUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '181','name' => 'Rwanda','isocode' => 'RW','currency_name' => 'Rwanda Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'RWF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '182','name' => 'Saint Helena','isocode' => 'SH','currency_name' => 'St. Helena Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SHP','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '183','name' => 'Saint Kitts & Nevis Anguilla','isocode' => 'KN','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '184','name' => 'Saint Lucia','isocode' => 'LC','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '185','name' => 'Saint Pierre and Miquelon','isocode' => 'PM','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '186','name' => 'Saint Vincent & Grenadines','isocode' => 'VC','currency_name' => 'East Caribbean Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'XCD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '187','name' => 'Samoa','isocode' => 'WS','currency_name' => 'Samoan Tala','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'WST','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '188','name' => 'San Marino','isocode' => 'SM','currency_name' => 'Italian Lira','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ITL','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '189','name' => 'Sao Tome and Principe','isocode' => 'ST','currency_name' => 'Dobra','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'STD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '190','name' => 'Saudi Arabia','isocode' => 'SA','currency_name' => 'Saudi Riyal','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SAR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '191','name' => 'Senegal','isocode' => 'SN','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '192','name' => 'Seychelles','isocode' => 'SC','currency_name' => 'Seychelles Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SCR','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '193','name' => 'Sierra Leone','isocode' => 'SL','currency_name' => 'Sierra Leone Leone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SLL','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '194','name' => 'Singapore','isocode' => 'SG','currency_name' => 'Singapore Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'SGD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '195','name' => 'Slovakia','isocode' => 'SK','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '196','name' => 'Slovenia','isocode' => 'SI','currency_name' => 'Slovenian Tolar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SIT','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '197','name' => 'Solomon Islands','isocode' => 'SB','currency_name' => 'Solomon Islands Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'SBD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '198','name' => 'Somalia','isocode' => 'SO','currency_name' => 'Somali Shilling','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SOD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '199','name' => 'South Africa','isocode' => 'ZA','currency_name' => 'South African Rand','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ZAR','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '200','name' => 'South Georgia & South Sandwich Islands','isocode' => 'GS','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '201','name' => 'Spain','isocode' => 'ES','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '202','name' => 'Sri Lanka','isocode' => 'LK','currency_name' => 'Sri Lanka Rupee','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'LKR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '203','name' => 'Sudan','isocode' => 'SD','currency_name' => 'Sudanese Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SDD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '204','name' => 'Suriname','isocode' => 'SR','currency_name' => 'Surinam Guilder','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SRG','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '205','name' => 'Svalbard and Jan Mayen Islands','isocode' => 'SJ','currency_name' => 'Norwegian Krone','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'NOK','has_regions' => '0','tax' => '0','continent' => '','visible' => '0'),
		array('id' => '206','name' => 'Swaziland','isocode' => 'SZ','currency_name' => 'Swaziland Lilangeni','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SZL','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '207','name' => 'Sweden','isocode' => 'SE','currency_name' => 'Swedish Krona','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SEK','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '208','name' => 'Switzerland','isocode' => 'CH','currency_name' => 'Swiss Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'CHF','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '209','name' => 'Syria','isocode' => 'SY','currency_name' => 'Syrian Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SYP','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '210','name' => 'Taiwan','isocode' => 'TW','currency_name' => 'Taiwan Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'TWD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '211','name' => 'Tajikistan','isocode' => 'TJ','currency_name' => 'Tajik Ruble','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TJR','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '212','name' => 'Tanzania','isocode' => 'TZ','currency_name' => 'Tanzanian Shilling','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TZS','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '213','name' => 'Thailand','isocode' => 'TH','currency_name' => 'Thai Baht','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'THB','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '214','name' => 'Togo','isocode' => 'TG','currency_name' => 'CFA Franc BCEAO','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XOF','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '215','name' => 'Tokelau','isocode' => 'TK','currency_name' => 'New Zealand Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'NZD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '216','name' => 'Tonga','isocode' => 'TO','currency_name' => 'Tongan Pa&#699;anga','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TOP','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '217','name' => 'Trinidad and Tobago','isocode' => 'TT','currency_name' => 'Trinidad and Tobago Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'TTD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '218','name' => 'Tunisia','isocode' => 'TN','currency_name' => 'Tunisian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'TND','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '219','name' => 'Turkey','isocode' => 'TR','currency_name' => 'Turkish Lira','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TRL','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '220','name' => 'Turkmenistan','isocode' => 'TM','currency_name' => 'Manat','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'TMM','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '221','name' => 'Turks and Caicos Islands','isocode' => 'TC','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '222','name' => 'Tuvalu','isocode' => 'TV','currency_name' => 'Australian Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'AUD','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '223','name' => 'U.K.','isocode' => 'UK','currency_name' => 'Pound Sterling','currency_symbol' => '£','currency_symbol_html' => '&#163;','currency_code' => 'GBP','has_regions' => '0','tax' => '17.5','continent' => 'europe','visible' => '0'),
		array('id' => '224','name' => 'Uganda','isocode' => 'UG','currency_name' => 'Uganda Shilling','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'UGS','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '225','name' => 'Ukraine','isocode' => 'UA','currency_name' => 'Ukraine Hryvnia','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'UAG','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '226','name' => 'United Arab Emirates','isocode' => 'AE','currency_name' => 'Arab Emirates Dirham','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'AED','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '227','name' => 'Uruguay','isocode' => 'UY','currency_name' => 'Uruguayan Peso','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'UYP','has_regions' => '0','tax' => '0','continent' => 'southamerica','visible' => '0'),
		array('id' => '228','name' => 'USA Minor Outlying Islands','isocode' => 'UM','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => '','visible' => '0'),
		array('id' => '229','name' => 'Uzbekistan','isocode' => 'UZ','currency_name' => 'Uzbekistan Sum','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'UZS','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '230','name' => 'Vanuatu','isocode' => 'VU','currency_name' => 'Vanuatu Vatu','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'VUV','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '231','name' => 'Vatican','isocode' => 'VA','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '232','name' => 'Venezuela','isocode' => 'VE','currency_name' => 'Venezuelan Bolivar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'VUB','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '233','name' => 'Vietnam','isocode' => 'VN','currency_name' => 'Vietnamese Dong','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'VND','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '234','name' => 'Virgin Islands (British)','isocode' => 'VG','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '235','name' => 'Virgin Islands (USA)','isocode' => 'VI','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '0','tax' => '0','continent' => 'northamerica','visible' => '0'),
		array('id' => '236','name' => 'Wallis and Futuna Islands','isocode' => 'WF','currency_name' => 'CFP Franc','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'XPF','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '237','name' => 'Western Sahara','isocode' => 'EH','currency_name' => 'Moroccan Dirham','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'MAD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '238','name' => 'Yemen','isocode' => 'YE','currency_name' => 'Yemeni Rial','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'YER','has_regions' => '0','tax' => '0','continent' => 'asiapacific','visible' => '0'),
		array('id' => '239','name' => 'Yugoslavia','isocode' => 'YU','currency_name' => 'Yugoslav New Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'YUN','has_regions' => '0','tax' => '0','continent' => 'europe','visible' => '0'),
		array('id' => '240','name' => 'Zambia','isocode' => 'ZM','currency_name' => 'Zambian Kwacha','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'ZMK','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '241','name' => 'Zimbabwe','isocode' => 'ZW','currency_name' => 'Zimbabwe Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'ZWD','has_regions' => '0','tax' => '0','continent' => 'africa','visible' => '0'),
		array('id' => '242','name' => 'South Sudan','isocode' => 'SS','currency_name' => 'South Sudanese Pound','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'SSP','has_regions' => '','tax' => '','continent' => 'africa','visible' => '0'),
		array('id' => '243','name' => 'Serbia','isocode' => 'RS','currency_name' => 'Serbian Dinar','currency_symbol' => '','currency_symbol_html' => '','currency_code' => 'RSD','has_regions' => '','tax' => '','continent' => 'europe','visible' => '0'),
		array('id' => '244','name' => 'Montenegro','isocode' => 'ME','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '','tax' => '','continent' => 'europe','visible' => '0'),
		array('id' => '245','name' => 'Timor-Leste','isocode' => 'TL','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036','currency_code' => 'USD','has_regions' => '','tax' => '','continent' => 'asiapacific','visible' => '0'),
		array('id' => '246','name' => 'Aland Islands','isocode' => 'AX','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '','tax' => '','continent' => 'europe','visible' => '0'),
		array('id' => '247','name' => 'Saint Barthelemy','isocode' => 'BL','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '','tax' => '','continent' => 'europe','visible' => '0'),
		array('id' => '248','name' => 'Bonaire, Sint Eustatius and Saba','isocode' => 'BQ','currency_name' => 'US Dollar','currency_symbol' => '$','currency_symbol_html' => '&#036;','currency_code' => 'USD','has_regions' => '','tax' => '','continent' => 'southamerica','visible' => '0'),
		array('id' => '249','name' => 'Curacao','isocode' => 'CW','currency_name' => 'Netherlands Antillean Guilder','currency_symbol' => 'ƒ','currency_symbol_html' => '&#402;','currency_code' => 'ANG','has_regions' => '','tax' => '','continent' => 'southamerica','visible' => '0'),
		array('id' => '250','name' => 'Saint Martin (French Part)','isocode' => 'MF','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '','tax' => '','continent' => 'southamerica','visible' => '0'),
		array('id' => '251','name' => 'Palestinian Territories','isocode' => 'PS','currency_name' => 'Israeli New Sheqel','currency_symbol' => '?','currency_symbol_html' => '&#8362;','currency_code' => 'ILS','has_regions' => '','tax' => '','continent' => 'asiapacific','visible' => '0'),
		array('id' => '252','name' => 'Sint Maarten (Dutch Part)','isocode' => 'SX','currency_name' => 'Netherlands Antillean Guilder','currency_symbol' => 'ƒ','currency_symbol_html' => '&#402;','currency_code' => 'ANG','has_regions' => '','tax' => '','continent' => 'southamerica','visible' => '0'),
		array('id' => '253','name' => 'French Guiana','isocode' => 'GF','currency_name' => 'Euro','currency_symbol' => '€','currency_symbol_html' => '&#8364;','currency_code' => 'EUR','has_regions' => '','tax' => '','continent' => 'southamerica','visible' => '0')
	);


	/**
	 * Get or modify the countries data used to initalize WP eCommerce ccuntries data structures
	 *
	 * @since  4.1
	 *
	 * @param array array of associative arrays of country data, each array element should have the following required properties
	 *  country_id
	 *  country_name
	 *  country_iso_code
	 *  currency_name
	 *  currency_symbol
	 *  currency_symbol_html
	 *  currency_text_code
	 *  has_regions
	 *  tax
	 *  continent
	 *  visible
	 */
	$countries = apply_filters( 'wpsc_get_countries_data_array', $countries );
	return $countries;
}

function _wpsc_get_regions_data_array() {
	$regions = array(
		array('id' => '1','country_id' => '100','name' => 'Alberta','code' => 'AB','tax' => '0'),
		array('id' => '2','country_id' => '100','name' => 'British Columbia','code' => 'BC','tax' => '0'),
		array('id' => '3','country_id' => '100','name' => 'Manitoba','code' => 'MB','tax' => '0'),
		array('id' => '4','country_id' => '100','name' => 'New Brunswick','code' => 'NB','tax' => '0'),
		array('id' => '5','country_id' => '100','name' => 'Newfoundland and Labrador','code' => 'NL','tax' => '0'),
		array('id' => '6','country_id' => '100','name' => 'Northwest Territories','code' => 'NT','tax' => '0'),
		array('id' => '7','country_id' => '100','name' => 'Nova Scotia','code' => 'NS','tax' => '0'),
		array('id' => '8','country_id' => '100','name' => 'Nunavut','code' => 'NU','tax' => '0'),
		array('id' => '9','country_id' => '100','name' => 'Ontario','code' => 'ON','tax' => '0'),
		array('id' => '10','country_id' => '100','name' => 'Prince Edward Island','code' => 'PE','tax' => '0'),
		array('id' => '11','country_id' => '100','name' => 'Quebec','code' => 'QC','tax' => '0'),
		array('id' => '12','country_id' => '100','name' => 'Saskatchewan','code' => 'SK','tax' => '0'),
		array('id' => '13','country_id' => '100','name' => 'Yukon','code' => 'YT','tax' => '0'),
		array('id' => '14','country_id' => '136','name' => 'Alabama','code' => 'AL','tax' => '0'),
		array('id' => '15','country_id' => '136','name' => 'Alaska','code' => 'AK','tax' => '0'),
		array('id' => '16','country_id' => '136','name' => 'Arizona','code' => 'AZ','tax' => '0'),
		array('id' => '17','country_id' => '136','name' => 'Arkansas','code' => 'AR','tax' => '0'),
		array('id' => '18','country_id' => '136','name' => 'California','code' => 'CA','tax' => '0'),
		array('id' => '19','country_id' => '136','name' => 'Colorado','code' => 'CO','tax' => '0'),
		array('id' => '20','country_id' => '136','name' => 'Connecticut','code' => 'CT','tax' => '0'),
		array('id' => '21','country_id' => '136','name' => 'Delaware','code' => 'DE','tax' => '0'),
		array('id' => '22','country_id' => '136','name' => 'Florida','code' => 'FL','tax' => '0'),
		array('id' => '23','country_id' => '136','name' => 'Georgia','code' => 'GA','tax' => '0'),
		array('id' => '24','country_id' => '136','name' => 'Hawaii','code' => 'HI','tax' => '0'),
		array('id' => '25','country_id' => '136','name' => 'Idaho','code' => 'ID','tax' => '0'),
		array('id' => '26','country_id' => '136','name' => 'Illinois','code' => 'IL','tax' => '0'),
		array('id' => '27','country_id' => '136','name' => 'Indiana','code' => 'IN','tax' => '0'),
		array('id' => '28','country_id' => '136','name' => 'Iowa','code' => 'IA','tax' => '0'),
		array('id' => '29','country_id' => '136','name' => 'Kansas','code' => 'KS','tax' => '0'),
		array('id' => '30','country_id' => '136','name' => 'Kentucky','code' => 'KY','tax' => '0'),
		array('id' => '31','country_id' => '136','name' => 'Louisiana','code' => 'LA','tax' => '0'),
		array('id' => '32','country_id' => '136','name' => 'Maine','code' => 'ME','tax' => '0'),
		array('id' => '33','country_id' => '136','name' => 'Maryland','code' => 'MD','tax' => '0'),
		array('id' => '34','country_id' => '136','name' => 'Massachusetts','code' => 'MA','tax' => '0'),
		array('id' => '35','country_id' => '136','name' => 'Michigan','code' => 'MI','tax' => '0'),
		array('id' => '36','country_id' => '136','name' => 'Minnesota','code' => 'MN','tax' => '0'),
		array('id' => '37','country_id' => '136','name' => 'Mississippi','code' => 'MS','tax' => '0'),
		array('id' => '38','country_id' => '136','name' => 'Missouri','code' => 'MO','tax' => '0'),
		array('id' => '39','country_id' => '136','name' => 'Montana','code' => 'MT','tax' => '0'),
		array('id' => '40','country_id' => '136','name' => 'Nebraska','code' => 'NE','tax' => '0'),
		array('id' => '41','country_id' => '136','name' => 'Nevada','code' => 'NV','tax' => '0'),
		array('id' => '42','country_id' => '136','name' => 'New Hampshire','code' => 'NH','tax' => '0'),
		array('id' => '43','country_id' => '136','name' => 'New Jersey','code' => 'NJ','tax' => '0'),
		array('id' => '44','country_id' => '136','name' => 'New Mexico','code' => 'NM','tax' => '0'),
		array('id' => '45','country_id' => '136','name' => 'New York','code' => 'NY','tax' => '0'),
		array('id' => '46','country_id' => '136','name' => 'North Carolina','code' => 'NC','tax' => '0'),
		array('id' => '47','country_id' => '136','name' => 'North Dakota','code' => 'ND','tax' => '0'),
		array('id' => '48','country_id' => '136','name' => 'Ohio','code' => 'OH','tax' => '0'),
		array('id' => '49','country_id' => '136','name' => 'Oklahoma','code' => 'OK','tax' => '0'),
		array('id' => '50','country_id' => '136','name' => 'Oregon','code' => 'OR','tax' => '0'),
		array('id' => '51','country_id' => '136','name' => 'Pennsylvania','code' => 'PA','tax' => '0'),
		array('id' => '52','country_id' => '136','name' => 'Rhode Island','code' => 'RI','tax' => '0'),
		array('id' => '53','country_id' => '136','name' => 'South Carolina','code' => 'SC','tax' => '0'),
		array('id' => '54','country_id' => '136','name' => 'South Dakota','code' => 'SD','tax' => '0'),
		array('id' => '55','country_id' => '136','name' => 'Tennessee','code' => 'TN','tax' => '0'),
		array('id' => '56','country_id' => '136','name' => 'Texas','code' => 'TX','tax' => '0'),
		array('id' => '57','country_id' => '136','name' => 'Utah','code' => 'UT','tax' => '0'),
		array('id' => '58','country_id' => '136','name' => 'Vermont','code' => 'VT','tax' => '0'),
		array('id' => '59','country_id' => '136','name' => 'Virginia','code' => 'VA','tax' => '0'),
		array('id' => '60','country_id' => '136','name' => 'Washington','code' => 'WA','tax' => '0'),
		array('id' => '61','country_id' => '136','name' => 'Washington DC','code' => 'DC','tax' => '0'),
		array('id' => '62','country_id' => '136','name' => 'West Virginia','code' => 'WV','tax' => '0'),
		array('id' => '63','country_id' => '136','name' => 'Wisconsin','code' => 'WI','tax' => '0'),
		array('id' => '64','country_id' => '136','name' => 'Wyoming','code' => 'WY','tax' => '0')
	);


	/**
	 * Get or modify the countries data used to initalize WP eCommerce regions data structures
	 *
	 * @since  4.1
	 *
	 * @param array array of associative arrays of country data, each array element should have the following required properties
	 *  id
	 *  country_id
	 *  name
	 *  code
	 *  tax
	 */
	$regions = apply_filters( 'wpsc_get_regions_data_array', $regions );

	return $regions;
}

if ( defined( 'WPSC_LOAD_DEPRECATED' ) && WPSC_LOAD_DEPRECATED ) {
	if ( is_admin() ) {
		add_action( 'query', '_wpsc_check_for_countries_regions_changes', 10, 1 );
		function _wpsc_check_for_countries_regions_changes( $query ) {

			if ( is_admin() ) {
				$changing_a_table_we_care_about = ( false !== stripos( $query, WPSC_TABLE_CURRENCY_LIST ) )
				                                  || ( false !== stripos( $query, WPSC_TABLE_REGION_TAX ) );
				if ( $changing_a_table_we_care_about ) {
					if ( stripos( $query, 'update' ) || stripos( $query, 'delete' ) || stripos( $query, 'insert' ) ) {
						// delete the options to force them to rebuild on the next request
						delete_option( 'wpsc_legacy_countries_data' );
						delete_option( 'wpsc_legacy_regions_data' );
					}
				}
			}
		}
	}
}